<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Bundle\IdentityBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Departments: the one somebody belongs to, those they support, the position
 * that heads each and the modules' pairs each allows.
 */
final class Version20261004000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'identity_department, identity_user.department_id, identity_user_supports';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE identity_department (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(120) NOT NULL,
              allows JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              head_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B5F8D3B9D17F50A6 ON identity_department (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B5F8D3B9F41A619E ON identity_department (head_id)');
        $this->addSql('ALTER TABLE identity_department ADD CONSTRAINT FK_DEPT_HEAD FOREIGN KEY (head_id) REFERENCES identity_position (id) ON DELETE SET NULL');

        $this->addSql('ALTER TABLE identity_user ADD department_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE identity_user ADD CONSTRAINT FK_USER_DEPT FOREIGN KEY (department_id) REFERENCES identity_department (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_39E1FCDAE80F5DF ON identity_user (department_id)');

        $this->addSql('CREATE TABLE identity_user_supports (user_id INT NOT NULL, department_id INT NOT NULL, PRIMARY KEY (user_id, department_id))');
        $this->addSql('CREATE INDEX IDX_468261B0A76ED395 ON identity_user_supports (user_id)');
        $this->addSql('CREATE INDEX IDX_468261B0AE80F5DF ON identity_user_supports (department_id)');
        $this->addSql('ALTER TABLE identity_user_supports ADD CONSTRAINT FK_SUPPORTS_USER FOREIGN KEY (user_id) REFERENCES identity_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE identity_user_supports ADD CONSTRAINT FK_SUPPORTS_DEPT FOREIGN KEY (department_id) REFERENCES identity_department (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE identity_user_supports');
        $this->addSql('ALTER TABLE identity_user DROP CONSTRAINT FK_USER_DEPT');
        $this->addSql('DROP INDEX IDX_39E1FCDAE80F5DF');
        $this->addSql('ALTER TABLE identity_user DROP department_id');
        $this->addSql('DROP TABLE identity_department');
    }
}
