<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Bundle\IdentityBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The people: the position that carries somebody's permissions, and the
 * account they sign in with.
 */
final class Version20261002000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'identity_position, identity_user';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE identity_position (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(120) NOT NULL,
              grants JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C7B83CD17F50A6 ON identity_position (uuid)');

        $this->addSql(<<<'SQL'
            CREATE TABLE identity_user (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              first_name VARCHAR(100) NOT NULL,
              last_name VARCHAR(100) NOT NULL,
              tier VARCHAR(16) NOT NULL,
              active BOOLEAN NOT NULL,
              password VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              position_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39E1FCDE7927C74 ON identity_user (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39E1FCDD17F50A6 ON identity_user (uuid)');
        $this->addSql('CREATE INDEX IDX_39E1FCDDD842E46 ON identity_user (position_id)');

        // Removing a position leaves the people who held it with none; it
        // never removes a person.
        $this->addSql(<<<'SQL'
            ALTER TABLE
              identity_user
            ADD
              CONSTRAINT FK_39E1FCDDD842E46 FOREIGN KEY (position_id) REFERENCES identity_position (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE identity_user DROP CONSTRAINT FK_39E1FCDDD842E46');
        $this->addSql('DROP TABLE identity_user');
        $this->addSql('DROP TABLE identity_position');
    }
}
