<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Bundle\IdentityBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The line kept of each delete a Super Admin makes.
 */
final class Version20261006000800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'identity_deletion';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE identity_deletion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, by_name VARCHAR(160) NOT NULL, by_id INT DEFAULT NULL, kind VARCHAR(32) NOT NULL, reference VARCHAR(180) NOT NULL, title VARCHAR(180) NOT NULL, what_went JSON NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE identity_deletion');
    }
}
