<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Bundle\IdentityBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The links sent to people's addresses: to set a new password, or to accept
 * an invitation.
 */
final class Version20261003000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'identity_account_link';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE identity_account_link (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              purpose VARCHAR(16) NOT NULL,
              selector VARCHAR(32) NOT NULL,
              verifier_hash VARCHAR(64) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              account_id INT NOT NULL,
              sent_by_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8683520E9692E25D ON identity_account_link (selector)');
        $this->addSql('CREATE INDEX IDX_8683520E9B6B5FBA ON identity_account_link (account_id)');
        $this->addSql('CREATE INDEX IDX_8683520EA45BB98C ON identity_account_link (sent_by_id)');
        $this->addSql('ALTER TABLE identity_account_link ADD CONSTRAINT FK_ACCOUNT_LINK_ACCOUNT FOREIGN KEY (account_id) REFERENCES identity_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE identity_account_link ADD CONSTRAINT FK_ACCOUNT_LINK_SENT_BY FOREIGN KEY (sent_by_id) REFERENCES identity_user (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE identity_account_link');
    }
}
