<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Bundle\IdentityBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Offices: where somebody is posted, from when, and where a department sits.
 */
final class Version20261004000200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'identity_office, identity_user.posted_at_id, posted_since, identity_department.office_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE identity_office (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(120) NOT NULL,
              city VARCHAR(120) NOT NULL,
              country VARCHAR(80) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C906C254D17F50A6 ON identity_office (uuid)');

        $this->addSql('ALTER TABLE identity_user ADD posted_at_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE identity_user ADD posted_since TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE identity_user ADD CONSTRAINT FK_USER_POSTED_AT FOREIGN KEY (posted_at_id) REFERENCES identity_office (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_39E1FCDEFA78038 ON identity_user (posted_at_id)');

        $this->addSql('ALTER TABLE identity_department ADD office_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE identity_department ADD CONSTRAINT FK_DEPT_OFFICE FOREIGN KEY (office_id) REFERENCES identity_office (id)');
        $this->addSql('CREATE INDEX IDX_B5F8D3B9FFA0C224 ON identity_department (office_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE identity_department DROP CONSTRAINT FK_DEPT_OFFICE');
        $this->addSql('DROP INDEX IDX_B5F8D3B9FFA0C224');
        $this->addSql('ALTER TABLE identity_department DROP office_id');
        $this->addSql('ALTER TABLE identity_user DROP CONSTRAINT FK_USER_POSTED_AT');
        $this->addSql('DROP INDEX IDX_39E1FCDEFA78038');
        $this->addSql('ALTER TABLE identity_user DROP posted_at_id, DROP posted_since');
        $this->addSql('DROP TABLE identity_office');
    }
}
