<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Core\Tests\Core;

use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Component\Routing\RouterInterface;
use Vivutio\Bundle\IdentityBundle\Access\ConcernCatalogue;
use Vivutio\Bundle\IdentityBundle\Entity\Position;
use Vivutio\Bundle\IdentityBundle\Entity\User;
use Vivutio\Bundle\IdentityBundle\Enum\TierEnum;
use Vivutio\Contracts\Access\Grant;
use Vivutio\Core\Tests\Application\Kernel;
use Vivutio\Core\Tests\Core\Authority\CoreProbes;
use Vivutio\Core\Tests\Core\Authority\Person;
use Vivutio\Core\Tests\Core\Authority\Probe;
use Vivutio\Core\Tests\Core\Authority\RouteGates;

/**
 * The authority table: every route, called as every kind of person, compared
 * with the reviewed table committed beside this test.
 *
 * Nothing here decides what the outcome should be. The voters and the
 * firewall decide, exactly as they do for a real request, and the table holds
 * what was reviewed. A change in who may open what is a change to the table,
 * and fails until it is recorded and its diff is read:
 *
 *     VIVUTIO_RECORD_AUTHORITY_TABLE=1 vendor/bin/phpunit --filter AuthorityTableTest
 */
final class AuthorityTableTest extends MigrationsTestCase
{
    private const string TABLE = __DIR__.'/authority-table.md';

    private const string RECORD = 'VIVUTIO_RECORD_AUTHORITY_TABLE';

    private KernelBrowser $browser;

    private int $people = 0;

    protected function start(): void
    {
        $this->browser = static::createClient();
    }

    protected function setUp(): void
    {
        parent::setUp();

        $this->migrate();
    }

    public function testEveryRouteHasAProbe(): void
    {
        $routes = array_keys($this->gates());
        $probed = array_map(static fn (Probe $probe): string => $probe->route, CoreProbes::all());

        self::assertSame([], array_values(array_diff($routes, $probed)), 'These routes have no probe, so the table cannot say who may open them.');
        self::assertSame([], array_values(array_diff($probed, $routes)), 'These probes name routes that do not exist.');
    }

    public function testEveryRouteAnswersEveryKindOfPersonAsTheReviewedTableSays(): void
    {
        $table = $this->table();

        if ('1' === getenv(self::RECORD)) {
            file_put_contents(self::TABLE, $table);
            self::markTestIncomplete('The authority table was recorded. Read its diff before committing it.');
        }

        self::assertFileExists(self::TABLE, 'No reviewed table yet. Record it with '.self::RECORD.'=1 and read it.');
        self::assertSame(
            (string) file_get_contents(self::TABLE),
            $table,
            'Who may open what has changed. If the change is intended, record the table with '.self::RECORD.'=1 and review its diff; if not, a loophole has opened.',
        );
    }

    private function table(): string
    {
        $gates = $this->gates();

        $lines = [
            '# Authority table',
            '',
            'Every route of the core, called as every kind of person. Generated by',
            '`tests/Core/AuthorityTableTest.php`; a change fails the build until it is',
            'recorded with `VIVUTIO_RECORD_AUTHORITY_TABLE=1` and its diff is reviewed.',
        ];

        foreach (CoreProbes::all() as $probe) {
            $checked = $gates[$probe->route] ?? [];

            $lines[] = '';
            $lines[] = \sprintf('## %s: %s %s', $probe->route, $probe->method, $probe->path);
            $lines[] = '';
            $lines[] = 'Checks: '.([] === $checked ? 'nothing (an open route)' : '`'.implode('`, `', $checked).'`');
            $lines[] = '';
            $lines[] = '| Person | Outcome |';
            $lines[] = '|---|---|';

            foreach (Person::cases() as $person) {
                $lines[] = \sprintf('| %s | %s |', $person->value, $this->outcome($probe, $person, $checked));
            }
        }

        return implode("\n", $lines)."\n";
    }

    /**
     * @param list<string> $checked the attributes the route checks
     */
    private function outcome(Probe $probe, Person $person, array $checked): string
    {
        $this->browser->restart();

        $account = $this->person($person, $checked);
        if (null !== $account) {
            $this->browser->loginUser($account);
        }

        if (Person::DeactivatedWhileSignedIn === $person) {
            $this->connection()->executeStatement('UPDATE identity_user SET active = false WHERE id = ?', [$account?->getId()]);
        }

        $this->browser->request($probe->method, $probe->path, $probe->body);
        $response = $this->browser->getResponse();
        $status = $response->getStatusCode();

        self::assertLessThan(500, $status, \sprintf('%s %s as %s failed with %d: an error is never an answer.', $probe->method, $probe->path, $person->value, $status));

        if ($response->isRedirection()) {
            $to = (string) parse_url((string) $response->headers->get('Location'), \PHP_URL_PATH);

            return '/login' === $to ? 'sent to sign-in' : 'redirected to '.$to;
        }

        return match (true) {
            $response->isSuccessful() => 'allowed',
            403 === $status => 'refused',
            404 === $status => 'not found',
            default => 'answered '.$status,
        };
    }

    /**
     * The account a kind of person signs in with, or null for a stranger.
     *
     * @param list<string> $checked the attributes the route checks
     */
    private function person(Person $person, array $checked): ?User
    {
        $pairs = array_values(array_filter($checked, static fn (string $attribute): bool => null !== Grant::tryParse($attribute)));
        $everyPair = $this->catalogue()->positionPairs();

        return match ($person) {
            Person::Stranger => null,
            Person::DeactivatedWhileSignedIn => $this->account(TierEnum::Admin),
            Person::StaffWithoutPosition => $this->account(TierEnum::Staff),
            Person::StaffHoldingThePair => $this->account(TierEnum::Staff, $this->position(array_values(array_intersect($pairs, $everyPair)))),
            Person::StaffHoldingAllButThePair => $this->account(TierEnum::Staff, $this->position(array_values(array_diff($everyPair, $pairs)))),
            Person::Admin => $this->account(TierEnum::Admin),
            Person::SuperAdmin => $this->account(TierEnum::SuperAdmin),
        };
    }

    /**
     * @param list<string> $grants
     */
    private function position(array $grants): Position
    {
        $position = (new Position())->setName('Seat '.($this->people + 1))->setGrants($grants);
        $this->entityManager()->persist($position);

        return $position;
    }

    private function account(TierEnum $tier, ?Position $position = null): User
    {
        ++$this->people;

        $user = (new User())
            ->setEmail('person'.$this->people.'@vivutio-camps.example')
            ->setFirstName('Person')
            ->setLastName((string) $this->people)
            ->setTier($tier)
            ->setPosition($position)
            ->setPassword('a hash, never a password');

        $em = $this->entityManager();
        $em->persist($user);
        $em->flush();

        return $user;
    }

    /**
     * @return array<string, list<string>>
     */
    private function gates(): array
    {
        $router = static::getContainer()->get('router');
        self::assertInstanceOf(RouterInterface::class, $router);

        return RouteGates::of($router);
    }

    private function catalogue(): ConcernCatalogue
    {
        $catalogue = static::getContainer()->get(Kernel::CATALOGUE);
        self::assertInstanceOf(ConcernCatalogue::class, $catalogue);

        return $catalogue;
    }

    private function entityManager(): EntityManagerInterface
    {
        $em = static::getContainer()->get('doctrine.orm.entity_manager');
        self::assertInstanceOf(EntityManagerInterface::class, $em);

        return $em;
    }

    private function connection(): Connection
    {
        $connection = static::getContainer()->get('doctrine.dbal.default_connection');
        self::assertInstanceOf(Connection::class, $connection);

        return $connection;
    }
}
