<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Bundle\PartnerBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Partners: the organizations an installation trades with, their contact,
 * their terms and the channel each is reached by.
 */
final class Version20261006000400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'partner';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE partner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(120) NOT NULL, kind VARCHAR(24) NOT NULL, country VARCHAR(2) NOT NULL, email VARCHAR(180) NOT NULL, contact VARCHAR(120) NOT NULL, phone VARCHAR(40) NOT NULL, discount NUMERIC(5, 2) NOT NULL, credit_days INT NOT NULL, channel VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL, notes TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_312B3E16D17F50A6 ON partner (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_312B3E165E237E06 ON partner (name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE partner');
    }
}
