<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Bundle\PlaceBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Destinations and their fees, with the parks and reserves of East Africa
 * shipped under the keys the hub knows them by. No fee is shipped: fees
 * change, and an installation enters those it charges.
 */
final class Version20261006000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'place_destination and place_destination_fee, with East Africa\'s parks and reserves';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE place_destination (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "key" VARCHAR(64) NOT NULL, name VARCHAR(120) NOT NULL, kind VARCHAR(24) NOT NULL, country VARCHAR(2) NOT NULL, shipped BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3033760EF48571EB ON place_destination ("key")');
        $this->addSql('CREATE TABLE place_destination_fee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(16) NOT NULL, guest VARCHAR(16) NOT NULL, residency VARCHAR(16) NOT NULL, per VARCHAR(16) NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, valid_from DATE NOT NULL, valid_to DATE NOT NULL, destination_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B9334B02816C6140 ON place_destination_fee (destination_id)');
        $this->addSql('ALTER TABLE place_destination_fee ADD CONSTRAINT FK_B9334B02816C6140 FOREIGN KEY (destination_id) REFERENCES place_destination (id) ON DELETE CASCADE');
        $this->addSql(<<<'SQL'
            INSERT INTO place_destination ("key", name, kind, country, shipped) VALUES
            ('tz-serengeti', 'Serengeti National Park', 'national_park', 'TZ', true),
            ('tz-ngorongoro', 'Ngorongoro Conservation Area', 'conservation_area', 'TZ', true),
            ('tz-tarangire', 'Tarangire National Park', 'national_park', 'TZ', true),
            ('tz-lake-manyara', 'Lake Manyara National Park', 'national_park', 'TZ', true),
            ('tz-arusha', 'Arusha National Park', 'national_park', 'TZ', true),
            ('tz-kilimanjaro', 'Kilimanjaro National Park', 'mountain', 'TZ', true),
            ('tz-ruaha', 'Ruaha National Park', 'national_park', 'TZ', true),
            ('tz-nyerere', 'Nyerere National Park', 'national_park', 'TZ', true),
            ('tz-mikumi', 'Mikumi National Park', 'national_park', 'TZ', true),
            ('tz-katavi', 'Katavi National Park', 'national_park', 'TZ', true),
            ('tz-mahale', 'Mahale Mountains National Park', 'national_park', 'TZ', true),
            ('tz-gombe', 'Gombe Stream National Park', 'national_park', 'TZ', true),
            ('tz-jozani', 'Jozani Chwaka Bay National Park', 'forest', 'TZ', true),
            ('tz-stone-town', 'Stone Town', 'city', 'TZ', true),
            ('ke-maasai-mara', 'Maasai Mara National Reserve', 'game_reserve', 'KE', true),
            ('ke-amboseli', 'Amboseli National Park', 'national_park', 'KE', true),
            ('ke-tsavo-east', 'Tsavo East National Park', 'national_park', 'KE', true),
            ('ke-tsavo-west', 'Tsavo West National Park', 'national_park', 'KE', true),
            ('ke-lake-nakuru', 'Lake Nakuru National Park', 'national_park', 'KE', true),
            ('ke-samburu', 'Samburu National Reserve', 'game_reserve', 'KE', true),
            ('ke-nairobi', 'Nairobi National Park', 'national_park', 'KE', true),
            ('ke-ol-pejeta', 'Ol Pejeta Conservancy', 'conservancy', 'KE', true),
            ('ke-mount-kenya', 'Mount Kenya National Park', 'mountain', 'KE', true),
            ('ug-bwindi', 'Bwindi Impenetrable National Park', 'national_park', 'UG', true),
            ('ug-queen-elizabeth', 'Queen Elizabeth National Park', 'national_park', 'UG', true),
            ('ug-murchison-falls', 'Murchison Falls National Park', 'national_park', 'UG', true),
            ('ug-kibale', 'Kibale National Park', 'forest', 'UG', true),
            ('ug-lake-mburo', 'Lake Mburo National Park', 'national_park', 'UG', true),
            ('rw-volcanoes', 'Volcanoes National Park', 'national_park', 'RW', true),
            ('rw-akagera', 'Akagera National Park', 'national_park', 'RW', true),
            ('rw-nyungwe', 'Nyungwe National Park', 'forest', 'RW', true)
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE place_destination_fee');
        $this->addSql('DROP TABLE place_destination');
    }
}
